export const RATING_TAG = "safe";

// Keep the automatic quality hint intentionally small. It is disposable and
// is dropped before any user-authored content when the token budget gets tight.
export const QUALITY_SUFFIX = "masterpiece";

// Kept as a compatibility export for local audit scripts.
export const QUALITY_PREFIX = QUALITY_SUFFIX;

export const DEFAULT_NEGATIVE_PROMPT =
  "lowres, bad anatomy, bad hands, text, extra digits, cropped, worst quality, low quality, watermark, blurry";

const PROMPT_TAGS: Record<string, string> = {
  日系萌系: "anime style",
  古风仙侠: "ancient chinese fantasy, xianxia, elegant",
  赛博科幻: "cyberpunk, science fiction, neon city",
  机甲硬核: "mecha, mechanical armor, hard surface",
  水墨淡彩: "chinese ink wash painting, light colors",
  校园清新: "school life, fresh atmosphere",
  热血战斗: "dynamic action, intense battle",
  清冷治愈: "calm, cool palette, healing atmosphere",
  厚涂写实: "painterly, semi-realistic, thick painting",
  线稿简约: "clean lineart, minimalist illustration",
  原神风: "fantasy game illustration, ornate anime costume",
  火影忍者画风: "ninja anime aesthetic, cel shading",
  鬼灭之刃画风: "demonslayer style, original character",
  // Compatibility with selections saved before the LoRA integration.
  鬼灭之刃质感: "demonslayer style, original character",
  海贼王手绘风: "adventure manga aesthetic, expressive linework",
  罗小黑战记治愈风: "soft chinese animation aesthetic, cozy",
  "4K 高清": "high resolution",
  发丝清晰: "detailed individual hair strands",
  阴影柔和: "soft shadows",
  锐化聚焦: "sharp focus",
  低饱和: "low saturation",
  马卡龙色调: "pastel color palette",
  霓虹光效: "neon lighting, glow",
  双马尾: "twintails",
  高马尾: "high ponytail",
  短发狼尾: "short wolf cut",
  长卷发: "long wavy hair",
  呆毛: "ahoge",
  粉毛: "pink hair",
  蓝毛: "blue hair",
  "银发（异色发）": "silver hair",
  渐变发色: "gradient hair",
  大眼睛: "large expressive eyes",
  异瞳: "portrait, centered face, both eyes visible, heterochromia",
  浅杏眼: "light almond-shaped eyes",
  微笑唇: "gentle smile",
  脸红娇羞: "blush, shy",
  清冷眼眸: "cool detached gaze",
  元气挑眉: "raised eyebrow, energetic expression",
  雀斑: "freckles",
  泪痣: "mole under eye",
  猫耳: "cat ears",
  "狐耳（兽耳）": "fox ears",
  恶魔角: "demon horns",
  口罩遮脸: "face mask",
  圆框眼镜: "round glasses",
  方框眼镜: "square glasses",
  "JK 制服女生": "1girl, japanese school uniform",
  校草风男生:
    "1boy, solo, male focus, masculine face, handsome male student",
  "社团达人（动漫社）": "anime club member",
  "社团达人（汉服社）": "hanfu club member",
  学霸: "honor student, book",
  篮球运动系: "basketball player",
  足球运动系: "soccer player",
  傲娇: "tsundere",
  天然呆: "airhead, innocent expression",
  病娇: "yandere, intense gaze",
  中二: "chuunibyou, dramatic pose",
  温柔学长: "gentle senior boy",
  元气少女: "energetic girl",
  清冷御姐: "cool mature woman",
  腹黑少年: "mischievous boy, sly smile",
  "情侣头像（双人互动）": "1boy and 1girl, couple interaction, matching profile picture",
  "闺蜜头像（同款不同色）":
    "2girls, best friends, matching outfits, different colors, standing side by side",
  兄弟羁绊风: "2boys, brotherly bond",
  "JK 制服": "japanese school uniform",
  水手服: "sailor uniform",
  汉服: "hanfu",
  Lolita: "lolita fashion",
  校园西装: "school blazer",
  运动校服: "school tracksuit",
  工装: "utility wear, workwear",
  魔法学院服: "magic academy uniform",
  机甲战衣: "mecha bodysuit, mechanical armor",
  猫耳发带: "cat ear headband",
  星星发卡: "star hairclip",
  耳机: "headphones",
  项链: "necklace",
  书包: "carrying one school bag",
  棒球帽: "baseball cap",
  佩剑: "sword",
  魔法杖: "magic wand",
  围巾手套: "scarf, gloves",
  正面视角: "front view",
  侧脸: "profile",
  半身像: "upper body",
  全身像: "full body, wide shot, head-to-toe, feet visible",
  坐姿: "sitting",
  站姿: "standing",
  低头浅笑: "looking down, gentle smile",
  抬头望天: "looking up at sky",
  比耶: "peace sign",
  托腮: "hand on cheek",
  挥手: "waving",
  递情书:
    "outstretched hand, visible envelope, offering love letter to viewer",
  "背靠背（情侣）": "back-to-back couple",
  并肩走: "walking side by side",
  摸头杀: "head pat",
  对视微笑: "eye contact, smiling",
  吹樱花: "blowing cherry blossom petals",
  戴耳机听歌: "wearing headphones, listening to music",
  翻漫画书: "reading manga",
  打篮球:
    "full body, dribbling a basketball, visible basketball, playing basketball, dynamic pose",
  魔法施法: "casting magic, magic effects",
  战斗姿势: "battle pose, dynamic",
  樱花树下: "under cherry blossom tree, falling petals",
  教室窗边: "beside classroom window",
  操场跑道: "school running track",
  图书馆: "library",
  放学小路: "after-school street",
  天台: "school rooftop",
  星空下: "under starry sky",
  海边落日: "seaside sunset",
  雨夜公交站: "bus stop at rainy night",
  异世界森林: "fantasy forest",
  赛博朋克街道: "cyberpunk street, neon signs",
  古风庭院: "traditional chinese courtyard",
  纯白背景:
    "white background, simple background, pure white background",
  粉色背景: "plain pink background",
  蓝色背景: "plain blue background",
  渐变背景: "gradient background",
  模糊光斑: "bokeh background",
  留白设计: "negative space, minimalist background",
  元气满满: "cheerful, energetic",
  温柔治愈: "gentle, soothing",
  清冷疏离: "cool, distant",
  傲娇炸毛: "tsundere, flustered",
  害羞脸红: "shy, blush",
  热血激昂: "passionate, intense",
  厌世感: "world-weary expression",
  甜妹感: "sweet girl aesthetic",
  盐系: "clean cool aesthetic",
  氛围感: "cinematic atmosphere",
  高级小众: "editorial, refined niche aesthetic",
  甜而不腻: "subtle sweetness",
  酷飒拽: "cool, confident, edgy",
  微信头像: "profile picture, centered composition",
  "QQ 头像": "profile picture, centered composition",
  小红书头像: "social media avatar, centered composition",
  微博头像: "social media avatar, centered composition",
  正方形裁剪兼容: "square composition, centered subject",
  圆形裁剪兼容:
    "full body, wide shot, front view, centered subject, head-to-toe, feet visible, circular crop safe",
  无水印: "clean image, no watermark",
  高清无噪点: "high resolution, clean, low noise",
  不撞款: "original character design",
  小众设计: "distinctive niche design",
  社团海报构图: "poster-ready composition",
  // Legacy compatibility for older saved selections.
  "可商用（用于社团海报）": "poster-ready composition",
  "20 步采样": "",
  "CFG = 5（黄金组合）": "",
  "sharp focus（锐化）": "sharp focus",
  五官正常: "symmetrical face, correct facial features",
  无穿模: "coherent clothing, no clipping",
  发丝不模糊: "detailed hair, sharp hair strands",
  比例协调: "correct proportions",
};

export function toModelPrompt(value: string): string {
  return PROMPT_TAGS[value] ?? value;
}
